require:
  - rubocop-rake
  - rubocop-rspec



AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "spec/dummy/**/*"
    - "exe/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

RSpec/ExampleLength:
  Enabled: false
